steps:
  - id: 'build_dbt_runner_image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --file=deploy/Docker/dbt-runner/Dockerfile
      - --build-arg=GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}
      - --build-arg=PROJECT_ID=${_PROJECT_ID}
      - --build-arg=DBT_USER=${_DBT_USER}
      - --tag=${_IMAGE_NAME_DBT_RUNNER}:${_TAG}
      - .
substitutions:
  _TAG: <place_holder>
  _GOOGLE_APPLICATION_CREDENTIALS: <place_holder>
  _PROJECT_ID: <place_holder>
  _IMAGE_NAME_DBT_RUNNER: <place_holder>
  _DBT_USER: <place_holder>
timeout: 3600s
images:
  ${_IMAGE_NAME_DBT_RUNNER}:${_TAG}
options:
  logging: CLOUD_LOGGING_ONLY
