steps:
  - id: 'build_rfm_calculation_image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --file=deploy/Docker/rfm/Dockerfile
      - --build-arg=GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}
      - --build-arg=GOOGLE_APPLICATION_CREDENTIALS_AWESOME_COMPANY_DATA=${_GOOGLE_APPLICATION_CREDENTIALS_AWESOME_COMPANY_DATA}
      - --build-arg=PROJECT_ID=${_PROJECT_ID}
      - --build-arg=PROJECT_ID_awesome_company_DATA=${_PROJECT_ID_awesome_company_DATA}
      - --build-arg=ENV_NAME=${_ENV_NAME}
      - --tag=${_IMAGE_NAME_RFM}:${_TAG}
      - .
substitutions:
  _GOOGLE_APPLICATION_CREDENTIALS: <place_holder>
  _GOOGLE_APPLICATION_CREDENTIALS_AWESOME_COMPANY_DATA: <place_holder>
  _PROJECT_ID: <place_holder>
  _PROJECT_ID_awesome_company_DATA: <place_holder>
  _ENV_NAME: <place_holder>
  _IMAGE_NAME_RFM: <place_holder>
  _TAG: <place_holder>
timeout: 3600s
images:
  ${_IMAGE_NAME_RFM}:${_TAG}
options:
  logging: CLOUD_LOGGING_ONLY
